name: Build Dillonis.live
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3 
      with:
          node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run format 
      run: npm run format  
  
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3 
      with:
          node-version: 20 

    - name: Install dependencies
      run: npm install

    - name: Run dev script
      run: npm run dev

    - name: Run build script
      run: npm run build

    - name: Run preview script
      run: npm run preview
